language: python
python: 3.5
sudo: false

env:
  - TOX_ENV=py27-django17
  - TOX_ENV=py33-django17
  - TOX_ENV=py34-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py33-django18
  - TOX_ENV=py34-django18
  - TOX_ENV=py35-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py34-django19
  - TOX_ENV=py35-django19

install:
  - pip install tox

before_script:
  - psql -c 'create database netfields;' -U postgres

script:
  - tox -e $TOX_ENV
